name: Generate AI Changelog

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai

      - name: Generate AI Changelog
        run: python scripts/generate_changelog.py
        env:
          OPENAI_API_KEY: ${{ secrets.HF_API_TOKEN }}

      - name: Commit Changelog
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add CHANGELOG.md
          git commit -m "AI changelog update [skip ci]" || echo "No changes"
          git push
